language: java
sudo: false
matrix:
  include:
    - jdk: openjdk8
      env: GRADLE_PUBLISH=true
    - jdk: openjdk11
      env: GRADLE_PUBLISH=false
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/bb06ddbc2f1ed0c5ad2e
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - secure: UejbLERw4xmne57Bwqoi9qBoN7Lw7LRuV2KNlYx02twlSx21TIcw+q6CHVqqUp+xi9/yKfIeweGFozAJZhgH4biUrCYr+YdsFO66FqyEfrH0hJCw2n28wHJLkIHC5uwOBN2nej+VUbRJXOAFcvAUIRuaEbvMqS2DoQz6EMlx3cs=
  - secure: OTQZqW2dalf+HhbrpMCoqZqEaGHvvT6TXYZTab6jbKe0aEbzAveFVK0646JvdR5mOoD3BBi5OJv8Lz8H+pC2HzSqNHcdv6cwMPeGQyb+leH9LNTFUo+wLkU5+xyYXx5IvYAks3muST2Mb59uRiu/64bSSqFag++YSGIXJb/hCvc=
  - secure: MugqnicuNwlAnHTeNKpcSOAYTQbqHPnDRao0C/jR2GvbU+fWf1q4wrx5aBDNIYABiFVmeRKqhjHEW23yKIl1hYRuc71DDJD3imgD53/Jw2O3J10vl1/2sf1O8oLa7UoVRJyzPZ/rlBqWn1FHafIlq9qGOJBE14IgRSkwb+D5Sfc=
  - secure: Qosd/E9TNOvW8jBXKPMdkxYKRCtBdV2vD98OTDiM7xk7MqOgPQWPmru28yNUNzr9sR+FXSQ9r88NAYdd837zbBia+1YGDy4DB7synIxmvPLMrffYL6StrWiRDQiuD01WhMyyd2hPqj6jHE6Q0pJKACsH/FFBbUc1x/VIWBnSXBE=
  - secure: RpQkLsEuqWcgYa1qi+xGQEc3rJ5AnTjFmC93wpvzjbYRnsrP4T4S9/IDxEa1+GV5DLeqlG2iYSjf7Z8zu/8Zy2XqEwFhGqEOr4eOoZMkhrnEugboetDAs0CnbpRnmVv0MROeDH2BKX7YDQJ9JugPSnA27c0I1a8pG+vKiSsg/Fo=
  - secure: JTjOqJsWyuc1co/uWFZKhoczLuCg38T7l0/15lIrR+iEAIiO1VtqpzHEbZB7SIyWB+oMxikm7NZfpNdSA9zpxQ4J2JoIn3SdimaeixNN3UuJJ/AxcfzTC/5ZzIpoBFSmnJWiAmCi8aZUX5w5D+/YTdItHYz7buTjM7rDO4sEwMc=
